using System.Text.Json.Serialization;

namespace KalshiSharp.Models.WebSocket;

/// <summary>
/// Base class for all WebSocket responses received from Kalshi.
/// </summary>
[JsonPolymorphic(TypeDiscriminatorPropertyName = "type")]
[JsonDerivedType(typeof(OrderBookUpdate), "orderbook_delta")]
[JsonDerivedType(typeof(OrderBookSnapshot), "orderbook_snapshot")]
[JsonDerivedType(typeof(TradeUpdate), "trade")]
[JsonDerivedType(typeof(OrderUpdate), "user_order")]
[JsonDerivedType(typeof(FillUpdate), "fill")]
[JsonDerivedType(typeof(MarketPositionUpdate), "market_position")]
[JsonDerivedType(typeof(SubscriptionConfirmation), "subscribed")]
[JsonDerivedType(typeof(UnsubscriptionConfirmation), "unsubscribed")]
[JsonDerivedType(typeof(ErrorMessage), "error")]
[JsonDerivedType(typeof(OKMessage), "ok")]
[JsonDerivedType(typeof(TickerUpdate), "ticker")]
public abstract record WebSocketMessage
{
    /// <summary>
    /// Message type identifier.
    /// </summary>
    [JsonPropertyName("type")]
    public abstract string Type { get; }

    /// <summary>
    /// Server-generated subscription identifier (sid) used to identify the channel.
    /// </summary>
    [JsonPropertyName("sid")]
    public int Sid { get; init; }
}


/// <summary>
/// Base class for all WebSocket responses received from Kalshi, which contain a message.
/// </summary>
/// <typeparam name="T">Type of message body.</typeparam>
public abstract record WebSocketMessage<T> : WebSocketMessage 
    where T: class
{
    /// <summary>
    /// Response's message payload.
    /// </summary>
    [JsonPropertyName("msg")]
    public required T Message { get; set; }
}

/// <summary>
/// Confirmation that a subscription was successful.
/// </summary>
public sealed record SubscriptionConfirmation : WebSocketMessage<SubscriptionConfirmation.MessageBody>
{
    /// <inheritdoc/>
    public override string Type => "subscribed";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    public int Id { get; init; }

    public sealed record MessageBody
    {
        /// <summary>
        /// The channel that was subscribed to (e.g., "orderbook_delta", "trade").
        /// </summary>
        [JsonPropertyName("channel")]
        public string? Channel { get; init; }
    }
}

/// <summary>
/// Confirmation that an unsubscription was successful.
/// </summary>
public sealed record UnsubscriptionConfirmation : WebSocketMessage
{
    /// <inheritdoc/>
    public override string Type => "unsubscribed";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    [JsonPropertyName("id")]
    public int Id { get; init; }

    /// <summary>
    /// Sequential number that should be checked if you want to guarantee you received all the messages. Used for snapshot/delta consistency
    /// </summary>
    [JsonPropertyName("seq")]
    public int Seq { get; init; }
}

/// <summary>
/// OK message from the WebSocket server.
/// </summary>
public sealed record OKMessage : WebSocketMessage
{
    /// <inheritdoc/>
    public override string Type => "ok";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    [JsonPropertyName("id")]
    public int Id { get; init; }

    /// <summary>
    /// Sequential number that should be checked if you want to guarantee you received all the messages. Used for snapshot/delta consistency
    /// </summary>
    [JsonPropertyName("seq")]
    public int Seq { get; init; }

    /// <summary>
    /// Full list of market tickers after update
    /// </summary>
    [JsonPropertyName("market_tickers")]
    public IReadOnlyList<string>? MarketTickers { get; init; }

    /// <summary>
    /// Full list of market IDs after update.
    /// </summary>
    [JsonPropertyName("market_ids")]
    public IReadOnlyList<string>? MarketIds { get; init; }
}

/// <summary>
/// Error message from the WebSocket server.
/// </summary>
public sealed record ErrorMessage : WebSocketMessage<ErrorMessage.MessageBody>
{
    /// <inheritdoc/>
    public override string Type => "error";

    /// <summary>
    /// Unique ID of the command request. Generated by the client and should be unique within a WS session.
    /// </summary>
    public int Id { get; init; }

    public sealed record MessageBody
    {
        /// <summary>
        /// Error code.
        /// </summary>
        [JsonPropertyName("code")]
        public int Code { get; init; }

        /// <summary>
        /// Human-readable error message.
        /// </summary>
        [JsonPropertyName("msg")]
        public string? ErrorMessage { get; init; }

        /// <summary>
        /// Market UUID if error is market-specific.
        /// </summary>
        [JsonPropertyName("market_id")]
        public string? MarketId { get; init; }

        /// <summary>
        /// Market ticker if error is market-specific.
        /// </summary>
        [JsonPropertyName("market_ticker")]
        public string? MarketTicker { get; init; }
    }
}
